/* TIIN Deals — forecast revenue separately from cash actually received. */
(function () {
  'use strict';
  const KEY = 'tiin_deals_v1';
  let view = 'active';

  const ru = {
    title:'Сделки', add:'Новая сделка', forecast:'Воронка дохода', forecastRevenue:'Ожидаемая выручка', forecastProfit:'Ожидаемая прибыль', due:'К оплате', received:'Оплачено', active:'Активные', all:'Все', paid:'Оплачено', cancelled:'Отменена', lead:'Лид', awaiting:'Ожидание ответа', work:'В работе', invoice:'Счёт отправлен', waiting:'Ждёт оплаты', client:'Клиент / компания', date:'Плановая дата оплаты', amount:'Сумма договора', economics:'Экономика сделки', tax:'Налог', vat:'НДС (в сумме)', commission:'Комиссия / агентские', cost:'Себестоимость', labour:'Работа / подрядчики', other:'Прочие расходы', net:'Чистая прибыль', margin:'Маржинальность', pay:'Отметить оплату', payment:'Получить оплату', paidTotal:'Получено', remaining:'Осталось получить', partial:'Частичная оплата', save:'Сохранить', edit:'Изменить', delete:'Удалить', cancel:'Отмена', comment:'Комментарий', wallet:'Кошелёк', personal:'Личный', business:'Бизнес', status:'Статус', confirmDelete:'Удалить сделку?', noDeals:'Пока нет сделок', noDealsHint:'Создайте сделку — она попадёт в прогноз, а баланс изменится только после оплаты.', linkedIncome:'Оплата добавлена в доход', revert:'Отменить оплату', removeIncome:'Удалить связанную операцию', keepIncome:'Оставить доход', paymentDate:'Дата поступления', paymentAmount:'Сумма поступления', overpay:'Сумма больше остатка', invalid:'Заполните название и сумму'
  };
  function tx(key) { return ru[key] || key; }
  function esc(v) { return String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
  function read() { try { const d=JSON.parse(localStorage.getItem(KEY)||'[]'); return Array.isArray(d)?d:[]; } catch (_) { return []; } }
  function write(rows) { localStorage.setItem(KEY, JSON.stringify(rows)); }
  function deal(id) { return read().find(x => x.id === id); }
  function id() { return 'deal-' + Date.now() + '-' + Math.random().toString(36).slice(2,7); }
  function n(v) { return Math.max(0, Number(v) || 0); }
  function fixedCost(d) { return n(d.cost) + n(d.labour) + n(d.other); }
  // Contract amount includes VAT. All percentage deductions use the amount left after VAT.
  function revenueWithoutVat(d) { return Math.max(0, n(d.amount) - vat(d)); }
  function deductions(d) { return [
    { label:tx('tax'), amount:tax(d), category:'taxes' },
    { label:tx('vat'), amount:vat(d), category:'taxes' },
    { label:tx('commission'), amount:commission(d), category:'other_exp' },
    { label:tx('cost'), amount:n(d.cost), category:'other_exp' },
    { label:tx('labour'), amount:n(d.labour), category:'other_exp' },
    { label:tx('other'), amount:n(d.other), category:'other_exp' }
  ].filter(row => row.amount > 0); }
  function vat(d) { const rate=n(d.vatRate); return rate ? n(d.amount) * rate / (100 + rate) : 0; }
  function tax(d) { return revenueWithoutVat(d) * n(d.taxRate) / 100; }
  function commission(d) { return revenueWithoutVat(d) * n(d.commissionRate) / 100; }
  function net(d) { return revenueWithoutVat(d) - tax(d) - commission(d) - fixedCost(d); }
  function paid(d) { return (d.payments || []).reduce((s,p) => s + n(p.amount), 0); }
  function remaining(d) { return Math.max(0, n(d.amount) - paid(d)); }
  function status(d) { return paid(d) >= n(d.amount) && n(d.amount) > 0 ? 'paid' : d.status || 'lead'; }
  function statusLabel(s) { return ({lead:tx('lead'),awaiting:tx('awaiting'),work:tx('work'),invoice:tx('invoice'),waiting:tx('waiting'),paid:tx('paid'),cancelled:tx('cancelled')})[s] || tx('lead'); }
  function dateLabel(v) { if (!v) return ''; try { return new Date(v+'T00:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'short'}); } catch (_) { return v; } }
  function scoped(rows) { return currentWallet === 'all' ? rows : rows.filter(d => (d.wallet || 'personal') === currentWallet); }
  function metrics(rows) {
    const valid = rows.filter(d => status(d) !== 'cancelled');
    const open = valid.filter(d => status(d) !== 'paid');
    const due = open.filter(d => ['invoice','waiting'].includes(status(d)));
    const got = valid.reduce((s,d) => s + paid(d), 0);
    return { open, revenue:open.reduce((s,d)=>s+remaining(d),0), profit:open.reduce((s,d)=>s+Math.max(0, net(d) * (remaining(d)/Math.max(1,n(d.amount)))),0), due:due.reduce((s,d)=>s+remaining(d),0), got };
  }
  function ensure() {
    const templates = document.getElementById('templatesScroll');
    if (templates && !document.getElementById('dealsAccess')) {
      const b=document.createElement('button'); b.type='button'; b.id='dealsAccess'; b.className='template-chip planning-access deals-access'; b.innerHTML='🤝 <span>'+tx('title')+'</span>'; b.onclick=window.openDeals; templates.appendChild(b);
    }
    const container=document.querySelector('.container');
    if (container && !document.getElementById('tab-deals')) { const panel=document.createElement('div'); panel.id='tab-deals'; panel.className='tab-content'; container.appendChild(panel); }
  }
  function hero() {
    const data=metrics(scoped(read()));
    return '<section class="deals-forecast card"><div class="deals-forecast-head"><div><div class="planning-eyebrow">'+tx('forecast')+'</div><h3>💼 '+tx('title')+'</h3></div><button class="planning-add small" onclick="openDeals()">'+tx('all')+'</button></div><div class="deals-metrics"><div><small>'+tx('forecastRevenue')+'</small><b>'+fmt(data.revenue)+'</b></div><div><small>'+tx('forecastProfit')+'</small><b class="income">'+fmt(data.profit)+'</b></div><div><small>'+tx('due')+'</small><b class="gold">'+fmt(data.due)+'</b></div></div></section>';
  }
  function render() {
    ensure(); const host=document.getElementById('tab-deals'); if (!host) return;
    const all=scoped(read()); const m=metrics(all);
    const rows=all.filter(d => view==='all' || (view==='active' ? !['paid','cancelled'].includes(status(d)) : status(d)===view));
    host.innerHTML='<section class="planning-screen deals-screen"><div class="planning-header"><div><div class="planning-eyebrow">'+tx('forecast')+'</div><h2>🤝 '+tx('title')+'</h2></div><button class="planning-add" onclick="openDealModal()">＋ '+tx('add').replace('Новая ','')+'</button></div>'+summary(m)+'<div class="planning-filters">'+[['active',tx('active')],['waiting',tx('waiting')],['invoice',tx('invoice')],['paid',tx('paid')],['all',tx('all')]].map(x=>'<button class="'+(view===x[0]?'active':'')+'" onclick="setDealView(\''+x[0]+'\')">'+x[1]+'</button>').join('')+'</div>'+(rows.length?'<div class="deals-list">'+rows.map(card).join('')+'</div>':'<div class="planning-empty"><div class="planning-empty-icon">🤝</div><h3>'+tx('noDeals')+'</h3><p>'+tx('noDealsHint')+'</p><button class="btn btn-gold" onclick="openDealModal()">＋ '+tx('add')+'</button></div>')+'</section>';
  }
  function summary(m) { return '<div class="deals-summary"><div><small>'+tx('forecastRevenue')+'</small><b>'+fmt(m.revenue)+'</b></div><div><small>'+tx('forecastProfit')+'</small><b class="income">'+fmt(m.profit)+'</b></div><div><small>'+tx('due')+'</small><b class="gold">'+fmt(m.due)+'</b></div><div><small>'+tx('received')+'</small><b class="income">'+fmt(m.got)+'</b></div></div>'; }
  function card(d) { const st=status(d), full=n(d.amount), got=paid(d), pct=full?Math.min(100,Math.round(got/full*100)):0; return '<article class="deal-card"><div class="deal-card-top"><div><span class="deal-status '+st+'">'+esc(statusLabel(st))+'</span><h3 onclick="openDealModal(\''+d.id+'\')">'+esc(d.title)+'</h3><p>'+esc(d.client||'')+(d.plannedDate?' · '+dateLabel(d.plannedDate):'')+'</p></div><button class="planning-menu" onclick="openDealActions(\''+d.id+'\')">⋮</button></div><div class="deal-progress"><span style="width:'+pct+'%"></span></div><div class="deal-money"><div><small>'+tx('amount')+'</small><b>'+fmt(full)+'</b></div><div><small>'+tx('paidTotal')+'</small><b class="income">'+fmt(got)+'</b></div><div><small>'+tx('net')+'</small><b class="gold">'+fmt(net(d))+'</b></div></div><div class="deal-card-foot"><span>'+tx('remaining')+': <b>'+fmt(remaining(d))+'</b></span>'+(st!=='cancelled'?(st!=='paid'?'<button class="planning-add small" onclick="openDealPaymentModal(\''+d.id+'\')">＋ '+tx('payment')+'</button>':'<button class="planning-add small" onclick="openDealPayments(\''+d.id+'\')">'+tx('paidTotal')+'</button>'):'')+'</div></article>'; }
  function field(label,id,value,opts) { return '<div class="form-group"><label>'+label+'</label><input '+(opts||'')+' class="form-input" id="'+id+'" value="'+esc(value ?? '')+'"></div>'; }
  window.openDealModal=function(dealId) { const d=dealId?deal(dealId):null; const x=d||{title:'',client:'',amount:'',plannedDate:'',status:'lead',wallet:currentWallet==='business'?'business':'personal',taxRate:0,vatRate:16,commissionRate:0,cost:0,labour:0,other:0,comment:''}; document.getElementById('modal').innerHTML='<h3>'+ (d?tx('edit'):tx('add')) +'</h3>'+field('Название сделки','dealTitle',x.title,'placeholder="Например, рекламная кампания"')+field(tx('client'),'dealClient',x.client)+field(tx('amount'),'dealAmount',x.amount,'type="number" min="0" inputmode="decimal" oninput="dealPreview()"')+'<div class="planning-dual deal-date-status">'+field(tx('date'),'dealDate',x.plannedDate,'type="date"')+'<div class="form-group"><label>'+tx('status')+'</label><select class="form-input" id="dealStatus">'+['lead','awaiting','work','invoice','waiting','cancelled'].map(s=>'<option value="'+s+'" '+(x.status===s?'selected':'')+'>'+statusLabel(s)+'</option>').join('')+'</select></div></div><div class="form-group"><label>'+tx('wallet')+'</label><div class="chips" id="dealWallet">'+chip('personal','👤 '+tx('personal'),x.wallet!=='business')+chip('business','💼 '+tx('business'),x.wallet==='business')+'</div></div><div class="deal-economics"><div class="deal-economics-title">'+tx('economics')+'</div><div class="planning-dual">'+field(tx('tax')+' (%)','dealTaxRate',x.taxRate,'type="number" min="0" step="0.1" inputmode="decimal" oninput="dealPreview()"')+field(tx('vat')+' (%)','dealVatRate',x.vatRate ?? 16,'type="number" min="0" step="0.1" inputmode="decimal" oninput="dealPreview()"')+field(tx('commission')+' (%)','dealCommissionRate',x.commissionRate,'type="number" min="0" step="0.1" inputmode="decimal" oninput="dealPreview()"')+field(tx('cost'),'dealCost',x.cost,'type="number" min="0" inputmode="decimal" oninput="dealPreview()"')+field(tx('labour'),'dealLabour',x.labour,'type="number" min="0" inputmode="decimal" oninput="dealPreview()"')+field(tx('other'),'dealOther',x.other,'type="number" min="0" inputmode="decimal" oninput="dealPreview()"')+'</div><div class="deal-live-profit" id="dealPreview"></div></div>'+field(tx('comment'),'dealComment',x.comment,'placeholder="Необязательно"')+'<button class="btn btn-gold" style="width:100%;margin-top:8px" onclick="saveDeal('+(d?'\''+d.id+'\'':'null')+')">'+tx('save')+'</button>'; document.getElementById('modalOverlay').classList.add('open'); dealPreview(); };
  function chip(i,l,s){ return '<button type="button" class="chip '+(s?'selected':'')+'" data-id="'+i+'" onclick="selectChip(this)">'+l+'</button>'; }
  window.dealPreview=function(){ const x={amount:n(document.getElementById('dealAmount')?.value),taxRate:n(document.getElementById('dealTaxRate')?.value),vatRate:n(document.getElementById('dealVatRate')?.value),commissionRate:n(document.getElementById('dealCommissionRate')?.value),cost:n(document.getElementById('dealCost')?.value),labour:n(document.getElementById('dealLabour')?.value),other:n(document.getElementById('dealOther')?.value)}; const e=document.getElementById('dealPreview'); if(e)e.innerHTML=tx('net')+': <b>'+fmt(net(x))+'</b><span> · '+tx('margin')+' '+(x.amount?Math.round(net(x)/x.amount*100):0)+'%</span>'; };
  window.saveDeal=function(dealId){ const title=document.getElementById('dealTitle').value.trim(), amount=n(document.getElementById('dealAmount').value); if(!title||!amount){toast(tx('invalid'));return;} const rows=read(); let d=dealId?rows.find(x=>x.id===dealId):null; const attrs={title,client:document.getElementById('dealClient').value.trim(),amount,plannedDate:document.getElementById('dealDate').value||null,status:document.getElementById('dealStatus').value,wallet:document.querySelector('#dealWallet .chip.selected')?.dataset.id||'personal',taxRate:n(document.getElementById('dealTaxRate').value),vatRate:n(document.getElementById('dealVatRate').value),commissionRate:n(document.getElementById('dealCommissionRate').value),cost:n(document.getElementById('dealCost').value),labour:n(document.getElementById('dealLabour').value),other:n(document.getElementById('dealOther').value),comment:document.getElementById('dealComment').value.trim(),updatedAt:new Date().toISOString()}; if(d)Object.assign(d,attrs);else{d={id:id(),payments:[],createdAt:attrs.updatedAt,...attrs};rows.unshift(d);} write(rows);closeModal();render(); if(currentTab==='transactions') window.renderTransactions(); };
  window.openDealPaymentModal=function(dealId){ const d=deal(dealId); if(!d)return; document.getElementById('modal').innerHTML='<h3>'+tx('payment')+'</h3><p class="planning-modal-description">'+esc(d.title)+' · '+tx('remaining')+': '+fmt(remaining(d))+'</p>'+field(tx('paymentAmount'),'dealPaymentAmount',remaining(d),'type="number" min="0" inputmode="decimal"')+field(tx('paymentDate'),'dealPaymentDate',localDateString(),'type="date"')+'<button class="btn btn-gold" style="width:100%" onclick="confirmDealPayment(\''+d.id+'\')">'+tx('pay')+'</button>';document.getElementById('modalOverlay').classList.add('open');};
  window.confirmDealPayment=function(dealId){ const d=deal(dealId), amount=n(document.getElementById('dealPaymentAmount').value), date=document.getElementById('dealPaymentDate').value; if(!d||!amount||!date)return; if(amount>remaining(d)+.01){toast(tx('overpay'));return;} const dt=new Date(date+'T00:00:00'), y=dt.getFullYear(),m=dt.getMonth(), incomeId='deal-income-'+d.id+'-'+Date.now(), ratio=amount/Math.max(1,n(d.amount)), expenseIds=[]; const ts=getTxns(y,m); ts.push({id:incomeId,type:'income',amount,category:'business',comment:'Сделка: '+d.title,date,wallet:d.wallet||'personal',tags:['сделка'],dealId:d.id}); deductions(d).forEach(row=>{ const expenseAmount=Math.round(row.amount*ratio*100)/100; if(!expenseAmount)return; const expenseId='deal-expense-'+d.id+'-'+Date.now()+'-'+expenseIds.length; expenseIds.push(expenseId); ts.push({id:expenseId,type:'expense',amount:expenseAmount,category:row.category,comment:'Сделка: '+d.title+' — '+row.label,date,wallet:d.wallet||'personal',tags:['сделка'],dealId:d.id}); }); saveTxns(y,m,ts); const rows=read(), target=rows.find(x=>x.id===d.id);target.payments.push({id:id(),amount,date,transactionId:incomeId,expenseTransactionIds:expenseIds});if(remaining(target)===0)target.status='paid';target.updatedAt=new Date().toISOString();write(rows);closeModal();toast('В баланс добавлено чистыми: '+fmt(Math.max(0,amount-deductions(d).reduce((s,row)=>s+row.amount*ratio,0))));render();};
  window.openDealPayments=function(dealId){const d=deal(dealId);if(!d)return;const rows=(d.payments||[]).map(p=>'<div class="deal-payment-row"><span>'+dateLabel(p.date)+'</span><b>'+fmt(p.amount)+'</b><button class="btn btn-danger btn-sm" onclick="revertDealPayment(\''+d.id+'\',\''+p.id+'\')">'+tx('revert')+'</button></div>').join('');document.getElementById('modal').innerHTML='<h3>'+tx('paidTotal')+'</h3><p class="planning-modal-description">'+esc(d.title)+'</p><div class="deal-payments">'+rows+'</div><button class="tx-action-cancel" onclick="closeModal()">'+tx('cancel')+'</button>';document.getElementById('modalOverlay').classList.add('open');};
  window.revertDealPayment=function(dealId,paymentId){const rows=read(),d=rows.find(x=>x.id===dealId),p=d?.payments?.find(x=>x.id===paymentId);if(!d||!p)return;if(!confirm(tx('removeIncome')+'?'))return;const dt=new Date(p.date+'T00:00:00'), linked=[p.transactionId,...(p.expenseTransactionIds||[])];saveTxns(dt.getFullYear(),dt.getMonth(),getTxns(dt.getFullYear(),dt.getMonth()).filter(x=>!linked.map(String).includes(String(x.id))));d.payments=d.payments.filter(x=>x.id!==paymentId);if(d.status==='paid')d.status='waiting';d.updatedAt=new Date().toISOString();write(rows);closeModal();render();};
  window.setDealView=function(v){view=v;render();};
  window.openDeals=function(){ensure();switchTab('deals');};
  window.openDealActions=function(dealId){const d=deal(dealId);if(!d)return;document.getElementById('modal').innerHTML='<div class="tx-action-sheet"><div class="tx-action-title">'+esc(d.title)+'</div><button class="btn btn-gold" onclick="openDealModal(\''+d.id+'\')">'+tx('edit')+'</button><button class="btn btn-danger" style="width:100%;margin-top:10px" onclick="deleteDeal(\''+d.id+'\')">'+tx('delete')+'</button><button class="tx-action-cancel" onclick="closeModal()">'+tx('cancel')+'</button></div>';document.getElementById('modalOverlay').classList.add('open');};
  window.deleteDeal=function(dealId){const d=deal(dealId);if(!d||!confirm(tx('confirmDelete')))return;if((d.payments||[]).length){toast('Сначала отмените связанные оплаты');return;}write(read().filter(x=>x.id!==dealId));closeModal();render();};
  const oldRenderTab=window.renderTab; window.renderTab=function(){if(currentTab==='deals')render();else oldRenderTab();};
  const oldTransactions=window.renderTransactions; window.renderTransactions=function(){oldTransactions();if(currentTab==='transactions'){const host=document.getElementById('tab-transactions');if(host&&!host.querySelector('.deals-forecast'))host.insertAdjacentHTML('afterbegin',hero());}};
  const oldTemplates=window.renderTemplates; window.renderTemplates=function(){oldTemplates();ensure();};
  ensure();
}());
